-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

-- TODO: manual review — malformed env on line 16: GDK_BACKEND,wayland,x11,*
hl.env("QT_QPA_PLATFORM", "wayland;xcb")
hl.env("CLUTTER_BACKEND", "wayland")

hl.env("XDG_CURRENT_DESKTOP", "Hyprland")
hl.env("XDG_SESSION_DESKTOP", "Hyprland")
hl.env("XDG_SESSION_TYPE", "wayland")

hl.env("QT_AUTO_SCREEN_SCALE_FACTOR", "1")
hl.env("QT_WAYLAND_DISABLE_WINDOWDECORATION", "1")
hl.env("QT_QPA_PLATFORMTHEME", "qt5ct")
hl.env("QT_QPA_PLATFORMTHEME", "qt6ct")

hl.env("QT_QUICK_CONTROLS_STYLE", "org.hyprland.style")

hl.env("GDK_SCALE", "1")
hl.env("QT_SCALE_FACTOR", "1")
hl.env("XCURSOR_SIZE", "12")

hl.env("HYPRCURSOR_THEME", "Bibata-Modern-Ice")
hl.env("HYPRCURSOR_SIZE", "24")

hl.env("MOZ_ENABLE_WAYLAND", "1")

hl.env("ELECTRON_OZONE_PLATFORM_HINT", "auto")

hl.env("LIBVA_DRIVER_NAME", "nvidia")
hl.env("__GLX_VENDOR_LIBRARY_NAME", "nvidia")
hl.env("NVD_BACKEND", "direct")

hl.env("GBM_BACKEND", "nvidia-drm")

hl.env("__GL_GSYNC_ALLOWED", "1")
hl.env("__NV_PRIME_RENDER_OFFLOAD", "1")
hl.env("__VK_LAYER_NV_optimus", "NVIDIA_only")
hl.env("WLR_DRM_NO_ATOMIC", "1")
hl.env("WLR_DRM_DEVICES", "/dev/dri/card0")

hl.env("TERM", "xterm-256color")
hl.env("GTK_IM_MODULE", "simple")
hl.config({
    debug = {
        disable_logs = false,
    },
})

hl.on("hyprland.start", function()
    hl.exec_cmd("nm-applet --indicator")
    hl.exec_cmd("swaync")
    hl.exec_cmd("blueman-applet")
    hl.exec_cmd("echo 0018:04F3:2F2C.0002 | sudo tee /sys/bus/hid/drivers/hid-multitouch/un")
    hl.exec_cmd("dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
    hl.exec_cmd("systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
    hl.exec_cmd("brightnessctl -d platform::micmute set 0")
    hl.exec_cmd("wpctl set-mute @DEFAULT_SOURCE@ true;")
    hl.exec_cmd("caelestia shell -d")
    hl.exec_cmd("qs -c overview")
end)
