

-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.window_rule({
    match = {
        class = "class:^([Ff]irefox|org.mozilla.firefox|[Ff]irefox-esr|[Ff]irefox-bin)$",
    },
    tag = "+browser",
})

hl.window_rule({
    match = {
        class = "class:^([Gg]oogle-chrome(-beta|-dev|-unstable)?)$",
    },
    tag = "+browser",
})

hl.window_rule({
    match = {
        class = "class:^(chrome-.+-Default)$",
    },
    tag = "+browser",
})

hl.window_rule({
    match = {
        class = "class:^([Cc]hromium)$",
    },
    tag = "+browser",
})

hl.window_rule({
    match = {
        class = "class:^([Mm]icrosoft-edge(-stable|-beta|-dev|-unstable))$",
    },
    tag = "+browser",
})

hl.window_rule({
    match = {
        class = "class:^(Brave-browser(-beta|-dev|-unstable)?)$",
    },
    tag = "+browser",
})

hl.window_rule({
    match = {
        class = "class:^([Tt]horium-browser|[Cc]achy-browser)$",
    },
    tag = "+browser",
})

hl.window_rule({
    match = {
        class = "class:^(zen-alpha|zen)$",
    },
    tag = "+browser",
})

hl.window_rule({
    match = {
        class = "class:^(swaync-control-center|swaync-notification-window|swaync-client|class)$",
    },
    tag = "+notif",
})

hl.window_rule({
    match = {
        class = "class:^(Alacritty|kitty|kitty-dropterm|ghostty)$",
    },
    tag = "+terminal",
})

hl.window_rule({
    match = {
        class = "class:^([Tt]hunderbird|org.gnome.Evolution)$",
    },
    tag = "+email",
})

hl.window_rule({
    match = {
        class = "class:^(eu.betterbird.Betterbird)$",
    },
    tag = "+email",
})

hl.window_rule({
    match = {
        class = "class:^(codium|codium-url-handler|VSCodium)$",
    },
    tag = "+projects",
})

hl.window_rule({
    match = {
        class = "class:^(VSCode|code-url-handler)$",
    },
    tag = "+projects",
})

hl.window_rule({
    match = {
        class = "class:^(jetbrains-.+)$",
    },
    tag = "+projects",
})

hl.window_rule({
    match = {
        class = "class:^(com.obsproject.Studio)$",
    },
    tag = "+screenshare",
})

hl.window_rule({
    match = {
        class = "class:^([Dd]iscord|[Ww]ebCord|[Vv]esktop)$",
    },
    tag = "+im",
})

hl.window_rule({
    match = {
        class = "class:^([Ff]erdium)$",
    },
    tag = "+im",
})

hl.window_rule({
    match = {
        class = "class:^([Ww]hatsapp-for-linux)$",
    },
    tag = "+im",
})

hl.window_rule({
    match = {
        class = "class:^(ZapZap|com.rtosta.zapzap)$",
    },
    tag = "+im",
})

hl.window_rule({
    match = {
        class = "class:^(org.telegram.desktop|io.github.tdesktop_x64.TDesktop)$",
    },
    tag = "+im",
})

hl.window_rule({
    match = {
        class = "class:^(teams-for-linux)$",
    },
    tag = "+im",
})

hl.window_rule({
    match = {
        class = "class:^(gamescope)$",
    },
    tag = "+games",
})

hl.window_rule({
    match = {
        class = "class:^(steam_app_\\d+)$",
    },
    tag = "+games",
})

hl.window_rule({
    match = {
        class = "class:^([Ss]team)$",
    },
    tag = "+gamestore",
})

hl.window_rule({
    match = {
        class = "title:^([Ll]utris)$",
    },
    tag = "+gamestore",
})

hl.window_rule({
    match = {
        class = "class:^(com.heroicgameslauncher.hgl)$",
    },
    tag = "+gamestore",
})

hl.window_rule({
    match = {
        class = "class:^([Tt]hunar|org.gnome.Nautilus|[Pp]cmanfm-qt)$",
    },
    tag = "+file-manager",
})

hl.window_rule({
    match = {
        class = "class:^(app.drey.Warp)$",
    },
    tag = "+file-manager",
})

hl.window_rule({
    match = {
        class = "class:^([Ww]aytrogen)$",
    },
    tag = "+wallpaper",
})

hl.window_rule({
    match = {
        class = "class:^([Aa]udacious)$",
    },
    tag = "+multimedia",
})

hl.window_rule({
    match = {
        class = "class:^([Mm]pv|vlc)$",
    },
    tag = "+multimedia_video",
})

hl.window_rule({
    match = {
        class = "title:^(ROG Control)$",
    },
    tag = "+settings",
})

hl.window_rule({
    match = {
        class = "class:^(wihotspot(-gui)?)$",
    },
    tag = "+settings",
})

hl.window_rule({
    match = {
        class = "class:^([Bb]aobab|org.gnome.[Bb]aobab)$",
    },
    tag = "+settings",
})

hl.window_rule({
    match = {
        class = "class:^(gnome-disks|wihotspot(-gui)?)$",
    },
    tag = "+settings",
})

hl.window_rule({
    match = {
        class = "title:(Kvantum Manager)",
    },
    tag = "+settings",
})

hl.window_rule({
    match = {
        class = "class:^(file-roller|org.gnome.FileRoller)$",
    },
    tag = "+settings",
})

hl.window_rule({
    match = {
        class = "class:^(nm-applet|nm-connection-editor|blueman-manager)$",
    },
    tag = "+settings",
})

hl.window_rule({
    match = {
        class = "class:^(pavucontrol|org.pulseaudio.pavucontrol|com.saivert.pwvucontrol)$",
    },
    tag = "+settings",
})

hl.window_rule({
    match = {
        class = "class:^(qt5ct|qt6ct|[Yy]ad)$",
    },
    tag = "+settings",
})

hl.window_rule({
    match = {
        class = "class:(xdg-desktop-portal-gtk)",
    },
    tag = "+settings",
})

hl.window_rule({
    match = {
        class = "class:^(org.kde.polkit-kde-authentication-agent-1)$",
    },
    tag = "+settings",
})

hl.window_rule({
    match = {
        class = "class:^([Rr]ofi)$",
    },
    tag = "+settings",
})

hl.window_rule({
    match = {
        class = "class:^(gnome-system-monitor|org.gnome.SystemMonitor|io.missioncenter.MissionCenter)$",
    },
    tag = "+viewer",
})

hl.window_rule({
    match = {
        class = "class:^(evince)$",
    },
    tag = "+viewer",
})

hl.window_rule({
    match = {
        class = "class:^(eog|org.gnome.Loupe)$",
    },
    tag = "+viewer",
})

hl.window_rule({
    match = {
        class = "tag:multimedia_video*",
    },
    opacity = 1.0,
})

hl.window_rule({
    match = {
        class = "tag:KooL_Cheat*",
    },
    center = true,
})

hl.window_rule({
    match = {
        class = "class:([Tt]hunar)$",
    },
    center = true,
})

hl.window_rule({
    match = {
        class = "title:^(ROG Control)$",
    },
    center = true,
})

hl.window_rule({
    match = {
        class = "tag:KooL-Settings*",
    },
    center = true,
})

hl.window_rule({
    match = {
        class = "title:^(Keybindings)$",
    },
    center = true,
})

hl.window_rule({
    match = {
        class = "class:^(pavucontrol|org.pulseaudio.pavucontrol|com.saivert.pwvucontrol)$",
    },
    center = true,
})

hl.window_rule({
    match = {
        class = "class:^([Ww]hatsapp-for-linux|ZapZap|com.rtosta.zapzap)$",
    },
    center = true,
})

hl.window_rule({
    match = {
        class = "class:^([Ff]erdium)$",
    },
    center = true,
})

hl.window_rule({
    match = {
        class = "title:^(Picture-in-Picture)$",
    },
    move = "72% 7%",
})

hl.window_rule({
    match = {
        class = "tag:email*",
    },
    workspace = "1",
})

hl.window_rule({
    match = {
        class = "tag:browser*",
    },
    workspace = "2",
})

hl.window_rule({
    match = {
        class = "tag:gamestore*",
    },
    workspace = "5",
})

hl.window_rule({
    match = {
        class = "tag:im*",
    },
    workspace = "7",
})

hl.window_rule({
    match = {
        class = "tag:games*",
    },
    workspace = "8",
})

hl.window_rule({
    match = {
        class = "tag:screenshare*",
    },
    workspace = "4 silent",
})

hl.window_rule({
    match = {
        class = "class:^(virt-manager)$",
    },
    workspace = "6 silent",
})

hl.window_rule({
    match = {
        class = "class:^(.virt-manager-wrapped)$",
    },
    workspace = "6 silent",
})

hl.window_rule({
    match = {
        class = "tag:multimedia*",
    },
    workspace = "9 silent",
})

hl.window_rule({
    match = {
        class = "tag:KooL_Cheat*",
    },
    float = true,
})

hl.window_rule({
    match = {
        class = "tag:wallpaper*",
    },
    float = true,
})

hl.window_rule({
    match = {
        class = "tag:settings*",
    },
    float = true,
})

hl.window_rule({
    match = {
        class = "tag:viewer*",
    },
    float = true,
})

hl.window_rule({
    match = {
        class = "tag:KooL-Settings*",
    },
    float = true,
})

hl.window_rule({
    match = {
        class = "class:([Zz]oom|onedriver|onedriver-launcher)$",
    },
    float = true,
})

hl.window_rule({
    match = {
        class = "class:^(mpv|com.github.rafostar.Clapper)$",
    },
    float = true,
})

hl.window_rule({
    match = {
        class = "class:^([Qq]alculate-gtk)$",
    },
    float = true,
})

hl.window_rule({
    match = {
        class = "class:^([Ff]erdium)$",
    },
    float = true,
})

hl.window_rule({
    match = {
        class = "title:^(Picture-in-Picture)$",
    },
    float = true,
})

hl.window_rule({
    match = {
        class = "title:^(Authentication Required)$",
    },
    float = true,
    center = true,
})

hl.window_rule({
    match = {
        class = "class:^(com.heroicgameslauncher.hgl)$",
    },
    float = true,
})

hl.window_rule({
    match = {
        class = "class:^([Ss]team)$",
    },
    float = true,
})

hl.window_rule({
    match = {
        class = "class:([Tt]hunar)$",
    },
    float = true,
})

hl.window_rule({
    match = {
        class = "title:^(Add Folder to Workspace)$",
    },
    float = true,
    size = "70% 60%",
    center = true,
})

hl.window_rule({
    match = {
        class = "title:^(Save As)$",
    },
    float = true,
    size = "70% 60%",
    center = true,
})

hl.window_rule({
    match = {
        class = "initialTitle:(Open Files)",
    },
    float = true,
    size = "70% 60%",
})

hl.window_rule({
    match = {
        class = "title:^(SDDM Background)$",
    },
    float = true,
    center = true,
    size = "16% 12%",
})

hl.window_rule({
    match = {
        class = "tag:browser*",
    },
    opacity = "1 0.7",
})

hl.window_rule({
    match = {
        class = "tag:projects*",
    },
    opacity = "0.9 0.8",
})

hl.window_rule({
    match = {
        class = "tag:im*",
    },
    opacity = "0.94 0.86",
})

hl.window_rule({
    match = {
        class = "tag:multimedia*",
    },
    opacity = "0.94 0.86",
})

hl.window_rule({
    match = {
        class = "tag:file-manager*",
    },
    opacity = "0.9 0.8",
})

hl.window_rule({
    match = {
        class = "tag:terminal*",
    },
    opacity = "0.8 0.7",
})

hl.window_rule({
    match = {
        class = "tag:settings*",
    },
    opacity = "0.8 0.7",
})

hl.window_rule({
    match = {
        class = "tag:viewer*",
    },
    opacity = "0.82 0.75",
})

hl.window_rule({
    match = {
        class = "tag:wallpaper*",
    },
    opacity = "0.9 0.7",
})

hl.window_rule({
    match = {
        class = "class:^(gedit|org.gnome.TextEditor|mousepad)$",
    },
    opacity = "0.8 0.7",
})

hl.window_rule({
    match = {
        class = "class:^(deluge)$",
    },
    opacity = "0.9 0.8",
})

hl.window_rule({
    match = {
        class = "class:^(im.riot.Riot)$",
    },
    opacity = "0.9 0.8",
})

hl.window_rule({
    match = {
        class = "class:^(seahorse)$",
    },
    opacity = "0.9 0.8",
})

hl.window_rule({
    match = {
        class = "title:^(Picture-in-Picture)$",
    },
    opacity = "0.95 0.75",
})

hl.window_rule({
    match = {
        class = "tag:KooL_Cheat*",
    },
    size = "65% 90%",
})

hl.window_rule({
    match = {
        class = "tag:wallpaper*",
    },
    size = "70% 70%",
})

hl.window_rule({
    match = {
        class = "tag:settings*",
    },
    size = "70% 70%",
})

hl.window_rule({
    match = {
        class = "class:^([Ww]hatsapp-for-linux|ZapZap|com.rtosta.zapzap)$",
    },
    size = "60% 70%",
})

hl.window_rule({
    match = {
        class = "class:^([Ff]erdium)$",
    },
    size = "60% 70%",
})

hl.window_rule({
    match = {
        class = "title:^(Picture-in-Picture)$",
    },
    pin = true,
})

hl.workspace_rule({
    workspace = "special:music",
    on_created_empty = "spotify"
})

hl.window_rule({
    match = {
        class = "^(Spotify)$",
    },
    workspace = "special:music",
})

hl.window_rule({
    match = {
        class = "tag:games*",
    },
    fullscreen = true,
})

hl.layer_rule({
    match = { namespace = "notifications" },
})
